export type Lang="zh"|"en";export type Category="science"|"art"|"sports"|"games"|"campus";
export type FeedCard={id:string;category:Category;emoji:string;title:Record<Lang,string>};
export const CATEGORY_META:Record<Category,{emoji:string;name:Record<Lang,string>;color:string}>={science:{emoji:"🔬",name:{zh:"科学",en:"SCIENCE"},color:"#4564ff"},art:{emoji:"🎨",name:{zh:"艺术",en:"ART"},color:"#ff5f57"},sports:{emoji:"🏀",name:{zh:"运动",en:"SPORTS"},color:"#f2a900"},games:{emoji:"🎮",name:{zh:"游戏",en:"GAMES"},color:"#12b7a6"},campus:{emoji:"🏫",name:{zh:"校园",en:"CAMPUS"},color:"#9b67d6"}};
export const CARDS:FeedCard[]=[
{id:"s1",category:"science",emoji:"🛰️",title:{zh:"中学生自制卫星收到第一组信号",en:"Students receive a signal from their homemade satellite"}},{id:"s2",category:"science",emoji:"🧪",title:{zh:"三分钟看懂为什么冰会浮起来",en:"Why ice floats—in three minutes"}},{id:"s3",category:"science",emoji:"🦠",title:{zh:"显微镜下的一滴池塘水",en:"One drop of pond water under a microscope"}},{id:"s4",category:"science",emoji:"🌌",title:{zh:"今晚能看见哪颗行星",en:"Which planet can you spot tonight?"}},
{id:"a1",category:"art",emoji:"🎹",title:{zh:"只用四个和弦写一段旋律",en:"Write a melody with four chords"}},{id:"a2",category:"art",emoji:"🧵",title:{zh:"旧校服变成像素布包",en:"Turn an old uniform into pixel art"}},{id:"a3",category:"art",emoji:"🎬",title:{zh:"一分钟定格动画幕后",en:"Behind a one-minute stop-motion film"}},{id:"a4",category:"art",emoji:"✏️",title:{zh:"光影让人物立起来的秘密",en:"How light makes a character feel real"}},
{id:"p1",category:"sports",emoji:"🏃",title:{zh:"接力赛交棒为什么总掉速",en:"Why relay handoffs lose speed"}},{id:"p2",category:"sports",emoji:"🧗",title:{zh:"攀岩路线的三种解法",en:"Three ways to solve a climbing route"}},{id:"p3",category:"sports",emoji:"⚽",title:{zh:"门将如何猜出点球方向",en:"How keepers predict a penalty"}},{id:"p4",category:"sports",emoji:"🛹",title:{zh:"滑板动作里的角动量",en:"Angular momentum in a skateboard trick"}},
{id:"g1",category:"games",emoji:"👾",title:{zh:"像素游戏为什么让人停不下来",en:"Why pixel games are hard to put down"}},{id:"g2",category:"games",emoji:"🗺️",title:{zh:"开放世界地图是怎么画出来的",en:"How open-world maps are designed"}},{id:"g3",category:"games",emoji:"🎲",title:{zh:"不用电脑也能设计一款游戏",en:"Design a game without a computer"}},{id:"g4",category:"games",emoji:"🕹️",title:{zh:"Boss 战难度曲线拆解",en:"Anatomy of a boss difficulty curve"}},
{id:"c1",category:"campus",emoji:"📚",title:{zh:"图书馆角落里的冷门好书",en:"Hidden gems in the school library"}},{id:"c2",category:"campus",emoji:"🌱",title:{zh:"屋顶菜园本周长了什么",en:"What grew in the rooftop garden"}},{id:"c3",category:"campus",emoji:"🎙️",title:{zh:"校园播客第一期上线",en:"The first campus podcast is live"}},{id:"c4",category:"campus",emoji:"🧹",title:{zh:"班级旧物交换计划",en:"The class swap-and-reuse plan"}}
];
export type Weights=Record<Category,number>;export const freshWeights=():Weights=>({science:1,art:1,sports:1,games:1,campus:1});
function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function chooseCard(seed:string,index:number,weights:Weights,seen:string[]){const available=CARDS.filter(c=>!seen.includes(c.id));const pool=available.length?available:CARDS;const scored=pool.map(card=>({card,score:weights[card.category]*1000+(hash(`${seed}:${index}:${card.id}`)%997)}));scored.sort((a,b)=>b.score-a.score);return scored[0].card}
export function updateWeights(weights:Weights,category:Category,liked:boolean):Weights{const next={...weights};next[category]=Math.max(.2,Math.min(12,next[category]+(liked?2:-.35)));return next}
export function diversityIndex(categories:Category[]){if(!categories.length)return 100;const counts={} as Record<Category,number>;for(const k of Object.keys(CATEGORY_META) as Category[])counts[k]=categories.filter(x=>x===k).length;let entropy=0;for(const n of Object.values(counts)){if(!n)continue;const p=n/categories.length;entropy-=p*Math.log(p)}return Math.round((entropy/Math.log(Object.keys(CATEGORY_META).length))*100)}
export const INTERVENTIONS=[{id:"reset",good:true,label:{zh:"重置或清理观看记录",en:"reset or clear watch history"}},{id:"diverse",good:true,label:{zh:"主动搜索不同主题与来源",en:"seek different topics and sources"}},{id:"control",good:true,label:{zh:"关闭个性化并查看时间线",en:"disable personalization and use chronological view"}},{id:"faster",good:false,label:{zh:"更快地连续点赞",en:"like similar posts even faster"}},{id:"block",good:false,label:{zh:"屏蔽所有不同意见",en:"block every different viewpoint"}},{id:"auto",good:false,label:{zh:"一直开着自动播放",en:"leave autoplay running forever"}}] as const;
export function interventionScore(ids:string[]){return Math.max(0,Math.min(100,ids.reduce((s,id)=>s+(INTERVENTIONS.find(x=>x.id===id)?.good?34:-18),0)))}
export function resultKey(score:number){return score>=85?"navigator":score>=65?"tamer":"passenger"}

