export type Lang="zh"|"en";export type Candidate={score:number;qualified:boolean};export type CourtCase={id:string;title:Record<Lang,string>;story:Record<Lang,string>;groupA:Record<Lang,string>;groupB:Record<Lang,string>;a:Candidate[];b:Candidate[];safeguards:{id:string;good:boolean;label:Record<Lang,string>}[];lesson:Record<Lang,string>};
const CASES:CourtCase[]=[
{id:"robot",title:{zh:"机器人联赛选拔",en:"ROBOT LEAGUE"},story:{zh:"模型根据旧比赛数据推荐 6 名训练队员，但两所分校过去得到的设备时间不同。",en:"A model recommends six trainees from past scores, but two campuses had unequal access to equipment."},groupA:{zh:"海风校区",en:"COAST CAMPUS"},groupB:{zh:"山谷校区",en:"VALLEY CAMPUS"},a:[{score:5,qualified:true},{score:5,qualified:true},{score:4,qualified:true},{score:4,qualified:true},{score:3,qualified:false}],b:[{score:4,qualified:true},{score:3,qualified:true},{score:3,qualified:true},{score:2,qualified:false},{score:2,qualified:false}],safeguards:[{id:"review",good:true,label:{zh:"给临界分选手一次作品复核",en:"review borderline portfolios"}},{id:"auto",good:false,label:{zh:"以后完全自动选拔",en:"make every future selection automatic"}}],lesson:{zh:"同一阈值看似一致，但历史机会不同时，结果可能仍然不公平。",en:"One threshold looks consistent, but unequal past opportunity can still create unfair outcomes."}},
{id:"library",title:{zh:"图书馆逾期提醒",en:"LIBRARY REMINDERS"},story:{zh:"系统预测谁可能逾期，并决定是否提前发提醒。错误提醒会打扰同学，漏发也会造成问题。",en:"A system predicts late returns and decides who gets an early reminder. False alerts annoy; missed alerts also hurt."},groupA:{zh:"纸质借阅",en:"PRINT BORROWERS"},groupB:{zh:"电子借阅",en:"E-READERS"},a:[{score:5,qualified:true},{score:4,qualified:true},{score:3,qualified:false},{score:2,qualified:false},{score:1,qualified:false}],b:[{score:5,qualified:true},{score:4,qualified:false},{score:4,qualified:false},{score:2,qualified:false},{score:1,qualified:false}],safeguards:[{id:"explain",good:true,label:{zh:"说明提醒原因并允许关闭",en:"explain alerts and allow opt-out"}},{id:"secret",good:false,label:{zh:"不公开系统如何判断",en:"keep every decision secret"}}],lesson:{zh:"公平不仅看通过率，还要比较误报、漏报和不同错误的代价。",en:"Fairness is not only selection rates—compare false alarms, misses and their costs."}},
{id:"garden",title:{zh:"屋顶花园排班",en:"ROOFTOP GARDEN"},story:{zh:"AI 按历史到场率分配热门时段，但旧记录里雨天值班被大量漏记。",en:"AI assigns popular shifts from attendance history, but many rainy-day shifts were never recorded."},groupA:{zh:"晴天小队",en:"SUN TEAM"},groupB:{zh:"雨天小队",en:"RAIN TEAM"},a:[{score:5,qualified:true},{score:4,qualified:true},{score:4,qualified:true},{score:3,qualified:false},{score:2,qualified:false}],b:[{score:3,qualified:true},{score:3,qualified:true},{score:2,qualified:true},{score:2,qualified:false},{score:1,qualified:false}],safeguards:[{id:"data",good:true,label:{zh:"先补录缺失记录再重新评估",en:"repair missing records before rerunning"}},{id:"blame",good:false,label:{zh:"直接认为低分就是不积极",en:"assume low scores mean low effort"}}],lesson:{zh:"缺失数据不是“没有发生”，先检查数据从哪里来、漏掉了谁。",en:"Missing data does not mean nothing happened. Check where data came from and who was omitted."}},
{id:"festival",title:{zh:"社团节摊位推荐",en:"CLUB FESTIVAL"},story:{zh:"系统按预测人气分配大厅摊位，新社团没有历史点击数据。",en:"A system assigns lobby booths by predicted popularity, but new clubs have no click history."},groupA:{zh:"老社团",en:"ESTABLISHED"},groupB:{zh:"新社团",en:"NEW CLUBS"},a:[{score:5,qualified:true},{score:5,qualified:true},{score:4,qualified:true},{score:3,qualified:false},{score:2,qualified:false}],b:[{score:3,qualified:true},{score:2,qualified:true},{score:2,qualified:false},{score:1,qualified:false},{score:1,qualified:false}],safeguards:[{id:"chance",good:true,label:{zh:"保留随机展示位并跟踪后续数据",en:"reserve random slots and monitor outcomes"}},{id:"history",good:false,label:{zh:"只相信历史点击量",en:"trust historical clicks only"}}],lesson:{zh:"纯粹优化历史表现会形成“越热门越有机会”的反馈循环。",en:"Optimizing past popularity alone creates a rich-get-richer feedback loop."}}
];
function hash(s:string){let h=0;for(const c of s)h=(Math.imul(h,31)+c.charCodeAt(0))|0;return h>>>0}export function casesForSeed(seed:string){const a=[...CASES],n=hash(seed);return a.map((_,i)=>a[(i+n)%a.length])}
export function metrics(c:CourtCase,threshold:number){const all=[...c.a.map(x=>({...x,g:"a"})),...c.b.map(x=>({...x,g:"b"}))];const accepted=(x:Candidate)=>x.score>=threshold;const correct=all.filter(x=>accepted(x)===x.qualified).length;const rate=(rows:Candidate[])=>Math.round(rows.filter(accepted).length/rows.length*100);const aRate=rate(c.a),bRate=rate(c.b);return{accuracy:Math.round(correct/all.length*100),aRate,bRate,gap:Math.abs(aRate-bRate)}}
export function verdictScore(c:CourtCase,threshold:number,safeguard:string){const m=metrics(c,threshold),responsible=c.safeguards.find(x=>x.id===safeguard)?.good?25:0;return{...m,responsible:responsible>0,score:Math.max(0,Math.min(100,Math.round(m.accuracy*.75-m.gap*.35+responsible)))}}
export function finalMastery(rows:{score:number}[]){return Math.round(rows.reduce((s,x)=>s+x.score,0)/Math.max(1,rows.length))}export function resultKey(v:number){return v>=85?"judge":v>=65?"clerk":"observer"}

