"use client";
import { useEffect, useState } from "react";
import { CLASSROOM_PACK_KEYS, CLASSROOM_PACKS, safeClassCode, type ClassroomPack } from "@/lib/ai-classrooms";
import { dx3xb, ensureSession, getEmail } from "@/app/dx3xb-trio";
import { persistLanguage } from "@/lib/language";

type Lang = "zh" | "en";
type Room = { code: string; title: string; pack: ClassroomPack; expires_at: string };
const C = {
  zh: { back:"← dx3xb", kicker:"AI 课堂挑战", title:"一串代码，全班进入同一组 AI 任务", desc:"学生不填姓名、不加入聊天。完成记录只以匿名总人数、完成数和平均掌握度显示给创建者。", joinTitle:"我是学生 / 参与者", joinDesc:"输入老师给的 6 位挑战码。", code:"挑战码", join:"进入挑战 →", invalid:"请输入正确的 6 位挑战码。", teacherTitle:"教师 / 社团组织者模式", teacherDesc:"创建课堂需要注册账号。每个课堂 14 天后自动到期，每天最多创建 8 个。", roomTitle:"活动名称（可选）", create:"创建挑战码", creating:"创建中…", login:"登录 / 注册后创建", created:"课堂已创建", copy:"复制课堂链接", copied:"已复制", dashboard:"打开教师看板 →", failed:"创建失败，请稍后再试。", packs:"选择活动包", expires:"有效期至", guide:"查看可打印活动包与教学建议 →", lang:"EN" },
  en: { back:"← dx3xb", kicker:"AI CLASS CHALLENGE", title:"One code puts the whole class on the same AI mission set", desc:"Students enter no names and join no chat. The creator sees only aggregate player counts, completions and average mastery.", joinTitle:"STUDENT / PARTICIPANT", joinDesc:"Enter the six-character challenge code from your teacher.", code:"CHALLENGE CODE", join:"JOIN CHALLENGE →", invalid:"Enter a valid six-character code.", teacherTitle:"TEACHER / CLUB ORGANIZER MODE", teacherDesc:"A registered account is required. Rooms expire after 14 days, with a limit of eight rooms per day.", roomTitle:"Activity title (optional)", create:"CREATE CHALLENGE CODE", creating:"CREATING…", login:"SIGN IN / REGISTER TO CREATE", created:"CLASSROOM CREATED", copy:"COPY CLASS LINK", copied:"COPIED", dashboard:"OPEN TEACHER DASHBOARD →", failed:"Could not create the room. Try again.", packs:"PICK AN ACTIVITY PACK", expires:"Expires", guide:"OPEN PRINTABLE ACTIVITY PACKS →", lang:"中" },
} as const;

export default function ClassroomHome() {
  const [lang,setLang]=useState<Lang>("zh"),[code,setCode]=useState(""),[selected,setSelected]=useState<ClassroomPack>("ai-foundations"),[title,setTitle]=useState(""),[email,setEmail]=useState<string|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[room,setRoom]=useState<Room|null>(null),[copied,setCopied]=useState(false);
  const t=C[lang];
  useEffect(()=>{const p=new URLSearchParams(location.search).get("lang"),l=p==="en"||(!p&&localStorage.getItem("dx3xb_lang")==="en")?"en":"zh";setLang(l);getEmail().then(setEmail).finally(()=>setLoaded(true))},[]);
  function switchLang(){const n=lang==="zh"?"en":"zh";setLang(n);persistLanguage(n);const u=new URL(location.href);u.searchParams.set("lang",n);history.replaceState(null,"",u)}
  function join(){const safe=safeClassCode(code);if(!safe){setError(t.invalid);return}location.href=`/class/${safe}?lang=${lang}`}
  async function create(){if(busy||!email)return;setBusy(true);setError("");try{await ensureSession();const{data}=await dx3xb().auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("session");const res=await fetch("/api/classrooms",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({pack:selected,title})});const body=await res.json();if(!res.ok||!body.classroom)throw new Error(body.error);setRoom(body.classroom)}catch{setError(t.failed)}finally{setBusy(false)}}
  async function copy(){if(!room)return;await navigator.clipboard.writeText(`${location.origin}/class/${room.code}?lang=${lang}`);setCopied(true);setTimeout(()=>setCopied(false),1500)}
  return <main className="wrap classroom"><style dangerouslySetInnerHTML={{__html:S}}/><div className="cbar"><a className="cbtn" href={`/?lang=${lang}`}>{t.back}</a><button className="cbtn" onClick={switchLang}>{t.lang}</button></div><header><p className="ckick">{t.kicker}</p><h1 className="pixel">{t.title}</h1><p>{t.desc}</p></header><div className="columns"><section className="panel join"><span aria-hidden="true">🎟️</span><h2 className="pixel">{t.joinTitle}</h2><p>{t.joinDesc}</p><label>{t.code}<input value={code} maxLength={6} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,""))} onKeyDown={e=>{if(e.key==="Enter")join()}} placeholder="ABC234" autoComplete="off"/></label><button className="cbtn coral" onClick={join}>{t.join}</button></section><section className="panel teacher"><span aria-hidden="true">🧑‍🏫</span><h2 className="pixel">{t.teacherTitle}</h2><p>{t.teacherDesc}</p><h3>{t.packs}</h3><div className="packs">{CLASSROOM_PACK_KEYS.map(key=>{const pack=CLASSROOM_PACKS[key];return <button key={key} className={selected===key?"on":""} onClick={()=>setSelected(key)}><b>{pack.name[lang]}</b><span>{pack.minutes} min · {pack.games.length} missions</span><small>{pack.desc[lang]}</small></button>})}</div><input className="titleInput" value={title} maxLength={60} onChange={e=>setTitle(e.target.value)} placeholder={t.roomTitle}/>{loaded&&email?<button className="cbtn coral" onClick={create} disabled={busy}>{busy?t.creating:t.create}</button>:<a className="cbtn" href={`/me?lang=${lang}`}>{t.login}</a>}{error&&<p className="error" role="alert">{error}</p>}</section></div>{room&&<section className="panel created"><div><span>{t.created}</span><b className="pixel">{room.code}</b><small>{t.expires} {new Date(room.expires_at).toLocaleDateString(lang==="zh"?"zh-CN":"en")}</small></div><button className="cbtn" onClick={copy}>{copied?t.copied:t.copy}</button><a className="cbtn coral" href={`/class/${room.code}?lang=${lang}&teacher=1`}>{t.dashboard}</a></section>}<a className="guide" href={`/class/activity-pack?lang=${lang}`}>📚 {t.guide}</a></main>
}
const S=`.classroom{max-width:980px;padding-bottom:70px}.cbar{display:flex;justify-content:space-between;margin-bottom:24px}.cbtn{display:inline-flex;justify-content:center;align-items:center;text-decoration:none;border:3px solid var(--line);box-shadow:3px 3px 0 var(--ink);background:#fff;color:var(--ink);padding:10px 13px;font:10px var(--font-press),monospace;cursor:pointer}.cbtn.coral{background:var(--coral);color:#fff}.cbtn:active{transform:translate(3px,3px);box-shadow:none}.classroom header{max-width:760px;margin-bottom:24px}.ckick{font:10px var(--font-press),monospace;color:var(--coral)}.classroom h1{font-size:clamp(29px,7vw,54px);line-height:1.15;margin:8px 0}.classroom header>p:last-child{font-size:20px;color:var(--ink-soft)}.columns{display:grid;grid-template-columns:.8fr 1.3fr;gap:18px}.join>span,.teacher>span{font-size:48px}.columns h2{font-size:14px;line-height:1.5}.join label{display:grid;gap:7px;font:9px var(--font-press),monospace;margin:22px 0}.join input{font:28px var(--font-press),monospace;letter-spacing:7px;text-transform:uppercase;border:4px solid var(--line);padding:14px;width:100%}.packs{display:grid;gap:9px;margin:12px 0}.packs button{text-align:left;background:#fff;border:3px solid var(--line);padding:12px;cursor:pointer;display:grid;gap:4px}.packs button.on{background:var(--yellow);box-shadow:4px 4px 0 var(--ink)}.packs span,.packs small{color:var(--ink-soft)}.titleInput{width:100%;border:3px solid var(--line);padding:12px;font:17px var(--font-body),sans-serif;margin:4px 0 12px}.error{color:#b42318}.created{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:18px;background:#d9f7e8}.created>div{display:grid;gap:6px}.created b{font-size:26px;letter-spacing:5px}.guide{display:block;color:var(--ink);margin-top:20px;font-weight:bold}@media(max-width:720px){.columns{grid-template-columns:1fr}.created{align-items:stretch;flex-direction:column}.classroom h1{font-size:clamp(27px,9vw,42px)}}`;

