create table if not exists dx3xb_private.ai_call_logs (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  route text not null check (route in ('generate','workshop')),
  model text not null,
  attempt integer not null check (attempt between 1 and 5),
  duration_ms integer not null check (duration_ms >= 0),
  http_status integer not null,
  outcome text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer not null default 0,
  estimated_cost_usd numeric(14,8) null,
  created_at timestamptz not null default now()
);
create index if not exists dx3xb_ai_call_logs_created_idx on dx3xb_private.ai_call_logs(created_at desc);
create index if not exists dx3xb_ai_call_logs_model_created_idx on dx3xb_private.ai_call_logs(model, created_at desc);
revoke all on dx3xb_private.ai_call_logs from public, anon, authenticated;
grant all on dx3xb_private.ai_call_logs to service_role;

create or replace function public.dx3xb_record_ai_call(
  p_request_id uuid, p_route text, p_model text, p_attempt integer, p_duration_ms integer,
  p_http_status integer, p_outcome text, p_input_tokens integer, p_output_tokens integer,
  p_total_tokens integer, p_estimated_cost_usd numeric
) returns boolean language plpgsql security definer set search_path = public, dx3xb_private, pg_temp as $$
begin
  insert into dx3xb_private.ai_call_logs(request_id,route,model,attempt,duration_ms,http_status,outcome,input_tokens,output_tokens,total_tokens,estimated_cost_usd)
  values (p_request_id,left(p_route,20),left(p_model,100),p_attempt,p_duration_ms,p_http_status,left(p_outcome,80),p_input_tokens,p_output_tokens,p_total_tokens,p_estimated_cost_usd);
  return true;
end;
$$;
revoke all on function public.dx3xb_record_ai_call(uuid,text,text,integer,integer,integer,text,integer,integer,integer,numeric) from public, anon, authenticated;
grant execute on function public.dx3xb_record_ai_call(uuid,text,text,integer,integer,integer,text,integer,integer,integer,numeric) to service_role;

create or replace function public.dx3xb_ai_cost_summary(p_days integer default 30) returns jsonb
language sql security definer set search_path = public, dx3xb_private, pg_temp as $$
  with filtered as materialized (
    select * from dx3xb_private.ai_call_logs
    where created_at >= now() - make_interval(days => least(greatest(p_days,1),90))
  ), totals as (
    select count(*) calls, count(*) filter (where outcome <> 'success') failures,
      coalesce(sum(input_tokens),0) input_tokens, coalesce(sum(output_tokens),0) output_tokens,
      coalesce(sum(total_tokens),0) total_tokens, coalesce(sum(estimated_cost_usd),0) cost,
      coalesce(round(avg(duration_ms)),0) average_duration from filtered
  ), daily as (
    select coalesce(jsonb_agg(row order by row->>'day'), '[]'::jsonb) rows from (
      select jsonb_build_object('day', created_at::date, 'calls', count(*), 'costUsd', coalesce(sum(estimated_cost_usd),0), 'tokens', coalesce(sum(total_tokens),0)) row
      from filtered group by created_at::date
    ) grouped
  )
  select jsonb_build_object('calls',calls,'failures',failures,'inputTokens',input_tokens,'outputTokens',output_tokens,
    'totalTokens',total_tokens,'estimatedCostUsd',cost,'averageDurationMs',average_duration,'byDay',daily.rows)
  from totals cross join daily;
$$;
revoke all on function public.dx3xb_ai_cost_summary(integer) from public, anon, authenticated;
grant execute on function public.dx3xb_ai_cost_summary(integer) to service_role;
