create table if not exists public.dx3xb_creator_follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  creator_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, creator_id),
  check (follower_id <> creator_id)
);

create table if not exists public.dx3xb_microapp_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  microapp_id uuid not null references public.dx3xb_microapps(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, microapp_id)
);

create table if not exists public.dx3xb_recent_plays (
  user_id uuid not null references auth.users(id) on delete cascade,
  microapp_id uuid not null references public.dx3xb_microapps(id) on delete cascade,
  played_at timestamptz not null default now(),
  primary key (user_id, microapp_id)
);
create index if not exists dx3xb_recent_plays_user_time_idx on public.dx3xb_recent_plays(user_id, played_at desc);

create table if not exists public.dx3xb_creator_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('creator_published', 'first_player', 'first_share')),
  microapp_id uuid not null references public.dx3xb_microapps(id) on delete cascade,
  actor_id uuid null references auth.users(id) on delete set null,
  read_at timestamptz null,
  created_at timestamptz not null default now()
);
create index if not exists dx3xb_notifications_user_time_idx on public.dx3xb_creator_notifications(user_id, created_at desc);

create table if not exists dx3xb_private.funnel_events (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  microapp_id uuid null references public.dx3xb_microapps(id) on delete cascade,
  event text not null check (event in ('workshop_enter','generation_start','generation_success','publish','first_player','first_share')),
  request_id uuid null,
  created_at timestamptz not null default now()
);
create index if not exists dx3xb_funnel_event_time_idx on dx3xb_private.funnel_events(event, created_at desc);
create unique index if not exists dx3xb_funnel_first_event_idx on dx3xb_private.funnel_events(microapp_id, event)
  where event in ('publish','first_player','first_share');

alter table public.dx3xb_creator_follows enable row level security;
alter table public.dx3xb_microapp_favorites enable row level security;
alter table public.dx3xb_recent_plays enable row level security;
alter table public.dx3xb_creator_notifications enable row level security;

drop policy if exists "follows own read" on public.dx3xb_creator_follows;
create policy "follows own read" on public.dx3xb_creator_follows for select to authenticated
  using (follower_id = auth.uid());
drop policy if exists "follows own write" on public.dx3xb_creator_follows;
create policy "follows own write" on public.dx3xb_creator_follows for all to authenticated
  using (follower_id = auth.uid()) with check (follower_id = auth.uid());

drop policy if exists "favorites own" on public.dx3xb_microapp_favorites;
create policy "favorites own" on public.dx3xb_microapp_favorites for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "recent own" on public.dx3xb_recent_plays;
create policy "recent own" on public.dx3xb_recent_plays for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "notifications own read" on public.dx3xb_creator_notifications;
create policy "notifications own read" on public.dx3xb_creator_notifications for select to authenticated
  using (user_id = auth.uid());
drop policy if exists "notifications own update" on public.dx3xb_creator_notifications;
create policy "notifications own update" on public.dx3xb_creator_notifications for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

revoke all on public.dx3xb_creator_follows, public.dx3xb_microapp_favorites, public.dx3xb_recent_plays, public.dx3xb_creator_notifications from anon;
grant select, insert, delete on public.dx3xb_creator_follows, public.dx3xb_microapp_favorites, public.dx3xb_recent_plays to authenticated;
grant select, update on public.dx3xb_creator_notifications to authenticated;
grant all on public.dx3xb_creator_follows, public.dx3xb_microapp_favorites, public.dx3xb_recent_plays, public.dx3xb_creator_notifications to service_role;
revoke all on dx3xb_private.funnel_events from public, anon, authenticated;
grant all on dx3xb_private.funnel_events to service_role;

create or replace function dx3xb_private.notify_creator_followers() returns trigger
language plpgsql security definer set search_path = public, dx3xb_private, pg_temp as $$
begin
  if new.status = 'public' and old.status is distinct from 'public' then
    insert into public.dx3xb_creator_notifications(user_id, kind, microapp_id, actor_id)
      select follower_id, 'creator_published', new.id, new.owner_id
      from public.dx3xb_creator_follows where creator_id = new.owner_id;
    insert into dx3xb_private.funnel_events(user_id, microapp_id, event)
      values (new.owner_id, new.id, 'publish') on conflict do nothing;
  end if;
  return new;
end;
$$;
drop trigger if exists dx3xb_notify_creator_followers on public.dx3xb_microapps;
create trigger dx3xb_notify_creator_followers after update of status on public.dx3xb_microapps
for each row execute function dx3xb_private.notify_creator_followers();
