create table if not exists public.dx3xb_guestbook (
  id bigint generated always as identity primary key,
  name text not null,
  message text not null,
  created_at timestamptz not null default now(),
  parent_id bigint references public.dx3xb_guestbook(id) on delete cascade,
  ip text,
  country text,
  city text,
  region text,
  hidden boolean not null default false
);

create table if not exists public.dx3xb_microapps (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  slug text not null unique,
  title text not null default '',
  template text not null default 'quiz',
  config jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft','unlisted','pending','public','hidden')),
  plays integer not null default 0 check (plays >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dx3xb_microapp_events (
  id bigint generated by default as identity primary key,
  microapp_id uuid not null references public.dx3xb_microapps(id) on delete cascade,
  event text not null check (event in ('view','start','complete','share')),
  created_at timestamptz not null default now(),
  user_id uuid,
  session_id text
);

create table if not exists public.dx3xb_microapp_reports (
  id bigint generated always as identity primary key,
  microapp_id uuid references public.dx3xb_microapps(id) on delete cascade,
  reason text,
  created_at timestamptz default now()
);

create table if not exists public.dx3xb_play_results (
  id uuid primary key default gen_random_uuid(),
  microapp_id uuid not null references public.dx3xb_microapps(id) on delete cascade,
  label text not null,
  score integer check (score between 0 and 100),
  created_at timestamptz not null default now()
);

create table if not exists public.dx3xb_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  handle text,
  created_at timestamptz default now()
);

create table if not exists public.dx3xb_runs (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game text not null,
  score integer not null default 0,
  pct integer,
  title text,
  stats jsonb,
  lang text,
  created_at timestamptz default now()
);

create table if not exists public.dx3xb_subscribers (
  id bigint generated always as identity primary key,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.dx3xb_toys (
  id bigint generated always as identity primary key,
  slug text not null unique,
  title_zh text not null,
  title_en text not null,
  desc_zh text default '',
  desc_en text default '',
  icon text default '🧸',
  type text not null default 'external' check (type in ('external','internal')),
  url text default '',
  status text not null default 'coming_soon' check (status in ('live','coming_soon','maintenance','hidden')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists dx3xb_gb_parent_idx on public.dx3xb_guestbook(parent_id);
create index if not exists dx3xb_microapp_events_app_event_idx on public.dx3xb_microapp_events(microapp_id,event,created_at desc);
create index if not exists dx3xb_microapp_events_created_idx on public.dx3xb_microapp_events(created_at desc);
create index if not exists dx3xb_microapps_owner_idx on public.dx3xb_microapps(owner_id,updated_at desc);
create index if not exists dx3xb_microapps_public_idx on public.dx3xb_microapps(status,plays desc);
create index if not exists dx3xb_runs_user_game_idx on public.dx3xb_runs(user_id,game,created_at desc);
create unique index if not exists dx3xb_subscribers_email_idx on public.dx3xb_subscribers(lower(email));

create or replace function public.dx3xb_bump_play(app_slug text) returns void
language sql security definer set search_path = public
as $$ update public.dx3xb_microapps set plays = plays + 1 where slug = app_slug and status in ('unlisted','pending','public') $$;

create or replace function public.dx3xb_gb_ratelimit() returns trigger
language plpgsql set search_path = public, pg_temp
as $$
begin
  if new.ip is not null and new.ip <> '' then
    if (select count(*) from public.dx3xb_guestbook where ip = new.ip and created_at > now() - interval '1 minute') >= 5 then
      raise exception 'rate_limited';
    end if;
    if exists (
      select 1 from public.dx3xb_guestbook
       where ip = new.ip and lower(message) = lower(new.message) and created_at > now() - interval '24 hours'
    ) then raise exception 'duplicate_message'; end if;
  end if;
  if length(new.message) > 280 or array_length(regexp_split_to_array(lower(new.message), 'https?://|www\.'), 1) > 3 then
    raise exception 'spam';
  end if;
  return new;
end;
$$;

create or replace function public.dx3xb_ma_ratelimit() returns trigger
language plpgsql set search_path = public, pg_temp
as $$
begin
  if (select count(*) from public.dx3xb_microapps where owner_id = new.owner_id and created_at > now() - interval '1 hour') >= 12 then
    raise exception 'rate_limited';
  end if;
  return new;
end;
$$;

drop trigger if exists dx3xb_gb_rl on public.dx3xb_guestbook;
create trigger dx3xb_gb_rl before insert on public.dx3xb_guestbook for each row execute function public.dx3xb_gb_ratelimit();
drop trigger if exists dx3xb_ma_rl on public.dx3xb_microapps;
create trigger dx3xb_ma_rl before insert on public.dx3xb_microapps for each row execute function public.dx3xb_ma_ratelimit();

alter table public.dx3xb_guestbook enable row level security;
alter table public.dx3xb_microapp_events enable row level security;
alter table public.dx3xb_microapp_reports enable row level security;
alter table public.dx3xb_microapps enable row level security;
alter table public.dx3xb_play_results enable row level security;
alter table public.dx3xb_profiles enable row level security;
alter table public.dx3xb_runs enable row level security;
alter table public.dx3xb_subscribers enable row level security;
alter table public.dx3xb_toys enable row level security;

drop policy if exists "ma owner delete" on public.dx3xb_microapps;
drop policy if exists "ma owner insert draft" on public.dx3xb_microapps;
drop policy if exists "ma owner read" on public.dx3xb_microapps;
drop policy if exists "ma owner update pre_public" on public.dx3xb_microapps;
drop policy if exists "ma public read" on public.dx3xb_microapps;
create policy "ma owner delete" on public.dx3xb_microapps for delete to authenticated using (auth.uid() = owner_id);
create policy "ma owner insert draft" on public.dx3xb_microapps for insert to authenticated
  with check (auth.uid() = owner_id and status = 'draft' and (template <> 'workshop' or nullif(auth.jwt()->>'email','') is not null));
create policy "ma owner read" on public.dx3xb_microapps for select to authenticated using (auth.uid() = owner_id);
create policy "ma owner update pre_public" on public.dx3xb_microapps for update to authenticated
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id and status in ('draft','unlisted','pending') and (template <> 'workshop' or nullif(auth.jwt()->>'email','') is not null));

drop policy if exists "own profile insert" on public.dx3xb_profiles;
drop policy if exists "own profile read" on public.dx3xb_profiles;
drop policy if exists "own profile update" on public.dx3xb_profiles;
create policy "own profile insert" on public.dx3xb_profiles for insert to authenticated with check (auth.uid() = user_id);
create policy "own profile read" on public.dx3xb_profiles for select to authenticated using (auth.uid() = user_id);
create policy "own profile update" on public.dx3xb_profiles for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own runs insert" on public.dx3xb_runs;
drop policy if exists "own runs read" on public.dx3xb_runs;
create policy "own runs insert" on public.dx3xb_runs for insert to authenticated with check (auth.uid() = user_id);
create policy "own runs read" on public.dx3xb_runs for select to authenticated using (auth.uid() = user_id);

revoke all on public.dx3xb_guestbook, public.dx3xb_microapp_events, public.dx3xb_microapp_reports,
  public.dx3xb_play_results, public.dx3xb_subscribers, public.dx3xb_toys from anon, authenticated;
revoke all on public.dx3xb_microapps, public.dx3xb_profiles, public.dx3xb_runs from anon, authenticated;
grant select, insert, update, delete on public.dx3xb_microapps to authenticated;
grant select, insert, update on public.dx3xb_profiles to authenticated;
grant select, insert on public.dx3xb_runs to authenticated;
revoke all on sequence public.dx3xb_guestbook_id_seq, public.dx3xb_microapp_events_id_seq,
  public.dx3xb_microapp_reports_id_seq, public.dx3xb_runs_id_seq,
  public.dx3xb_subscribers_id_seq, public.dx3xb_toys_id_seq from anon, authenticated;
grant usage, select on sequence public.dx3xb_runs_id_seq to authenticated;
grant all on public.dx3xb_guestbook, public.dx3xb_microapp_events, public.dx3xb_microapp_reports,
  public.dx3xb_microapps, public.dx3xb_play_results, public.dx3xb_profiles, public.dx3xb_runs,
  public.dx3xb_subscribers, public.dx3xb_toys to service_role;
grant usage, select on all sequences in schema public to service_role;
