"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { toPng } from "html-to-image";
import QRCode from "qrcode";
import { AiQuestFooter,getAiProfile } from "./dx3xb-ai";
import { evaluatePrompt,finalMastery,missionsForSeed,resultKey,type Mission } from "./game";

type Lang="zh"|"en";type Phase="intro"|"play"|"feedback"|"result";type RoundResult={pct:number;success:boolean};
const C={zh:{kicker:"AI 探险 · 任务 03",title:"提示词指挥官",sub:"别和机器人猜谜。用有限指令，把任务讲到能执行。",intro:"提示词不是神秘咒语，而是一份任务说明。目标、上下文、限制、步骤和检查标准，缺一块都可能让机器人跑偏。",r1:"4 个任务，每次只能选有限指令",r2:"无运行时大模型：结果完全可验证",r3:"通关后直接改造官方游戏模板",start:"领取指挥权 →",task:(n:number)=>`任务 ${n}/4`,vague:"原始要求",build:"组装你的指令",budget:(n:number)=>`还可选择 ${n} 块`,execute:"执行指令 →",empty:"至少选择一块指令",robotOk:"任务完成",robotBad:"机器人卡住了",missing:"缺少的关键信息",next:"下一项任务 →",report:"查看指挥报告 →",mastery:"提示表达掌握度",success:(n:number)=>`${n}/4 成功执行`,lesson:"本关原理",reportKicker:"COMMAND REPORT",learning:"你刚刚练会了",learningText:"把模糊要求变成含目标、上下文、限制、步骤和验收标准的可执行指令；这比堆礼貌词或要求“更厉害”有效。",remixTitle:"从玩家变成创作者",remixDesc:"挑一个官方模板，改规则、画面或难度；AI 工坊会帮你实现并发布给同学玩。",remix:"改造官方模板 →",share:"分享挑战",copy:"复制链接",copied:"已复制",download:"保存战报",replay:"重新指挥",newSet:"换一组顺序",daily:"今日任务",classLabel:"班级挑战",lang:"EN",anon:"匿名指挥官",titles:{architect:["提示词架构师","你不是在许愿，你在写一份可验证的任务协议。"],commander:["任务指挥官","大多数任务能落地，再把遗漏的限制补齐。"],apprentice:["指令学徒","先说清做什么、给谁、不能怎样、如何算完成。"]} as Record<string,[string,string]>},en:{kicker:"AI ADVENTURE · MISSION 03",title:"Prompt Commander",sub:"Stop making the robot guess. Turn a vague request into an executable brief.",intro:"A prompt is not a magic spell. It is a task brief: goal, context, constraints, steps and checks keep an AI from drifting.",r1:"4 missions with a strict instruction budget",r2:"No runtime model: every outcome is verifiable",r3:"Remix official game templates after finishing",start:"TAKE COMMAND →",task:(n:number)=>`MISSION ${n}/4`,vague:"VAGUE REQUEST",build:"BUILD YOUR INSTRUCTION",budget:(n:number)=>`${n} blocks left`,execute:"RUN COMMAND →",empty:"Choose at least one instruction block",robotOk:"MISSION COMPLETE",robotBad:"ROBOT GOT STUCK",missing:"MISSING INFORMATION",next:"NEXT MISSION →",report:"OPEN COMMAND REPORT →",mastery:"prompt mastery",success:(n:number)=>`${n}/4 executed`,lesson:"MISSION PRINCIPLE",reportKicker:"COMMAND REPORT",learning:"WHAT YOU LEARNED",learningText:"Turn vague wishes into testable instructions with a goal, context, constraints, steps and completion checks. That beats filler words like “better” or “more epic.”",remixTitle:"GO FROM PLAYER TO CREATOR",remixDesc:"Pick an official template, change its rules, art or difficulty, then use the AI Workshop to build and publish it.",remix:"REMIX A TEMPLATE →",share:"SHARE CHALLENGE",copy:"COPY LINK",copied:"COPIED",download:"SAVE REPORT",replay:"PLAY AGAIN",newSet:"RESHUFFLE",daily:"DAILY MISSION",classLabel:"CLASS CHALLENGE",lang:"中",anon:"ANONYMOUS COMMANDER",titles:{architect:["PROMPT ARCHITECT","You write testable task protocols instead of making wishes."],commander:["MISSION COMMANDER","Most tasks land. Add the missing constraints for consistency."],apprentice:["COMMAND APPRENTICE","State what, for whom, what to avoid, and how to know it is done."]} as Record<string,[string,string]>}} as const;
function seedSafe(v:string|null){return(v||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,48)}function makeSeed(){return Math.random().toString(36).slice(2,10)}
export default function PromptCommander(){
 const[hydrated,setHydrated]=useState(false),[lang,setLang]=useState<Lang>("zh"),[seed,setSeed]=useState("prompt"),[phase,setPhase]=useState<Phase>("intro"),[index,setIndex]=useState(0),[selected,setSelected]=useState<string[]>([]),[rounds,setRounds]=useState<RoundResult[]>([]),[last,setLast]=useState<ReturnType<typeof evaluatePrompt>|null>(null),[profile,setProfile]=useState(""),[dailyDate,setDailyDate]=useState(""),[classCode,setClassCode]=useState(""),[qr,setQr]=useState(""),[copied,setCopied]=useState(false),[saving,setSaving]=useState(false);const reportRef=useRef<HTMLDivElement>(null);
 const missions=useMemo(()=>missionsForSeed(seed),[seed]),mission:Mission=missions[index],t=C[lang];const mastery=finalMastery(rounds),successes=rounds.filter(x=>x.success).length,title=t.titles[resultKey(mastery)],name=profile||t.anon,score=mastery*10+successes*75;
 useEffect(()=>{const p=new URLSearchParams(location.search),l=p.get("lang")==="en"||(!p.get("lang")&&localStorage.getItem("dx3xb_lang")==="en")?"en":"zh";setLang(l);setSeed(seedSafe(p.get("seed"))||makeSeed());setDailyDate(/^\d{4}-\d{2}-\d{2}$/.test(p.get("daily")||"")?p.get("daily")||"":"");setClassCode(/^[A-Z2-9]{6}$/.test((p.get("class")||"").toUpperCase())?(p.get("class")||"").toUpperCase():"");getAiProfile().then(x=>setProfile((x.handle||"").slice(0,24))).catch(()=>{});setHydrated(true)},[]);
 const challenge=useMemo(()=>{const u=new URL(typeof location==="undefined"?"https://prompt-commander.dx3xb.com":location.origin);u.searchParams.set("seed",seed);u.searchParams.set("lang",lang);if(classCode)u.searchParams.set("class",classCode);return u.toString()},[classCode,lang,seed]);
 useEffect(()=>{if(phase==="result")QRCode.toDataURL(challenge,{margin:1,width:220,color:{dark:"#221a2b",light:"#fffdf8"}}).then(setQr).catch(()=>setQr(""))},[challenge,phase]);
 function start(next=seed){setSeed(next);setPhase("play");setIndex(0);setSelected([]);setRounds([]);setLast(null)}function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<mission.budget?[...s,id]:s)}function execute(){if(!selected.length)return;const r=evaluatePrompt(mission,selected);setLast(r);setRounds(x=>[...x,{pct:r.pct,success:r.success}]);setPhase("feedback")}
 function advance(){if(index===missions.length-1)setPhase("result");else{setIndex(x=>x+1);setSelected([]);setLast(null);setPhase("play")}}function fresh(){const s=makeSeed(),u=new URL(location.href);u.searchParams.set("seed",s);u.searchParams.delete("daily");history.replaceState(null,"",u);setDailyDate("");start(s)}function switchLang(){const n=lang==="zh"?"en":"zh";setLang(n);localStorage.setItem("dx3xb_lang",n);const u=new URL(location.href);u.searchParams.set("lang",n);history.replaceState(null,"",u)}
 async function copy(){await navigator.clipboard.writeText(challenge);setCopied(true);setTimeout(()=>setCopied(false),1500)}async function share(){if(navigator.share)await navigator.share({title:t.title,text:title[0],url:challenge}).catch(()=>{});else await copy()}async function download(){if(!reportRef.current)return;setSaving(true);try{const url=await toPng(reportRef.current,{pixelRatio:2,backgroundColor:"#fff7e7"});const a=document.createElement("a");a.download=`dx3xb-prompt-${seed}.png`;a.href=url;a.click()}finally{setSaving(false)}}
 const run=useMemo(()=>({score,pct:mastery,title:title[0],lang,handle:name,stats:{seed,successes,total:4,rounds,...(dailyDate?{dailyDate}:{}),...(classCode?{classCode}:{})}}),[classCode,dailyDate,lang,mastery,name,rounds,score,seed,successes,title]);
 return <main className="wrap pcWrap" data-testid="game-root" data-hydrated={hydrated?"true":"false"}><style dangerouslySetInnerHTML={{__html:STYLE}}/><div className="backbar"><a className="backbtn" href="https://dx3xb.com">← dx3xb</a><button className="langbtn" onClick={switchLang}>{t.lang}</button></div><header className="pcHero"><div><p className="labKicker">{t.kicker}</p><h1 className="pixel title">{t.title}</h1><p className="subtitle pixel">{t.sub}</p></div><div className="robot" aria-hidden="true">🤖<i>⌨</i></div></header>{(dailyDate||classCode)&&<div className="missionStrip">{dailyDate&&<b>☀ {t.daily} · {dailyDate}</b>}{classCode&&<b>🏫 {t.classLabel} · {classCode}</b>}</div>}
 {phase==="intro"&&<section className="panel introPanel"><p className="introText">{t.intro}</p><div className="rules"><span>1</span><p>{t.r1}</p><span>2</span><p>{t.r2}</p><span>3</span><p>{t.r3}</p></div><button className="btn coral" onClick={()=>start()}>{t.start}</button></section>}
 {phase==="play"&&<section className="panel commandPanel"><div className="taskHead"><b className="pixel">{t.task(index+1)} · {mission.title[lang]}</b><span>{t.budget(mission.budget-selected.length)}</span></div><div className="scene" aria-label={mission.title[lang]}>{mission.scene.map((x,i)=><span key={i}>{x}</span>)}</div><div className="vague"><small className="pixel">{t.vague}</small><q>{mission.vague[lang]}</q></div><h2>{t.build}</h2><div className="chips">{mission.chips.map(chip=><button key={chip.id} className={selected.includes(chip.id)?"on":""} aria-pressed={selected.includes(chip.id)} onClick={()=>toggle(chip.id)} disabled={!selected.includes(chip.id)&&selected.length>=mission.budget}><span>{chip.text[lang]}</span><small>{chip.kind.toUpperCase()}</small></button>)}</div><div className="assembled">{selected.length?selected.map(id=>mission.chips.find(c=>c.id===id)?.text[lang]).join(" · "):t.empty}</div><button className="btn coral" disabled={!selected.length} onClick={execute}>{t.execute}</button></section>}
 {phase==="feedback"&&last&&<section className={`panel feedbackPanel ${last.success?"ok":"bad"}`}><div className="runRobot" aria-hidden="true"><span>🤖</span><i>{last.success?"→ → → 🏁":"→ → 💥"}</i></div><h2 className="pixel">{last.success?t.robotOk:t.robotBad}</h2>{last.missing.length>0&&<><p>{t.missing}</p><div className="missing">{last.missing.map(id=><b key={id}>{mission.chips.find(c=>c.id===id)?.text[lang]}</b>)}</div></>}<div className="lesson"><span className="pixel">{t.lesson}</span><strong>{mission.lesson[lang]}</strong></div><button className="btn coral" onClick={advance}>{index===missions.length-1?t.report:t.next}</button></section>}
 {phase==="result"&&<section className="resultShell"><div className="reportCard promptReport" ref={reportRef}><div className="reportTop"><p className="labKicker">{t.reportKicker}</p><span>SPEC COMPLETE</span></div><p className="issued">{name}</p><h2 className="pixel resultName">{title[0]}</h2><p className="resultDesc">{title[1]}</p><div className="mastery"><b>{mastery}<span>%</span></b><p>{t.mastery}</p></div><div className="reportGrid"><div><b>{successes}/4</b><span>{t.success(successes)}</span></div><div><b>{rounds.filter(x=>x.pct===100).length}</b><span>FULL SPEC</span></div><div><b>{rounds.reduce((s,x)=>s+x.pct,0)}</b><span>CLARITY PTS</span></div></div><div className="learningCard"><span className="pixel">{t.learning}</span><strong>{t.learningText}</strong></div><div className="reportShare">{qr&&<img src={qr} alt="challenge QR"/>}<div><p className="pixel">PROMPT COMMANDER</p><small>prompt-commander.dx3xb.com</small></div></div></div><div className="panel remixCard"><div aria-hidden="true">🛠️</div><div><h3 className="pixel">{t.remixTitle}</h3><p>{t.remixDesc}</p></div><a className="btn coral" href={`https://dx3xb.com/studio?remix=prompt-commander&lang=${lang}`}>{t.remix}</a></div><div className="actions resultActions"><button className="btn coral" onClick={download} disabled={saving}>{saving?"…":t.download}</button><button className="btn teal" onClick={share}>{t.share}</button><button className="btn ghost" onClick={copy}>{copied?t.copied:t.copy}</button><button className="btn ghost" onClick={()=>start()}>{t.replay}</button><button className="btn ghost" onClick={fresh}>{t.newSet}</button></div><AiQuestFooter lang={lang} run={run}/></section>}
 </main>}
const STYLE=`.pcWrap{max-width:900px}.pcHero{display:grid;grid-template-columns:1fr 170px;align-items:center;gap:22px}.robot{width:140px;height:140px;border:4px solid var(--line);background:var(--yellow);box-shadow:8px 8px 0 var(--ink);display:grid;place-items:center;font-size:70px;position:relative;transform:rotate(3deg)}.robot i{position:absolute;right:-12px;bottom:-10px;font:28px var(--font-press);background:var(--teal);border:3px solid var(--line);padding:5px}.missionStrip{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0 16px}.missionStrip b{background:var(--yellow);border:3px solid var(--line);padding:7px 10px;font:11px var(--font-press),monospace}.taskHead{display:flex;justify-content:space-between;gap:10px;align-items:center}.taskHead b{font-size:10px}.taskHead span{background:var(--yellow);border:2px solid var(--line);padding:5px 8px}.scene{display:grid;grid-template-columns:repeat(6,1fr);margin:16px 0}.scene span{aspect-ratio:1;display:grid;place-items:center;font-size:34px;background:#fff;border:3px solid var(--line)}.scene span+span{border-left:0}.vague{background:#eee8db;border:3px dashed var(--line);padding:12px;display:grid;gap:8px}.vague small{font-size:9px}.vague q{font-size:22px}.chips{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.chips button{text-align:left;border:3px solid var(--line);background:#fff;box-shadow:3px 3px 0 var(--ink);padding:12px;cursor:pointer;display:grid;gap:5px}.chips button.on{background:var(--teal);color:#fff;transform:translate(3px,3px);box-shadow:none}.chips button:disabled{opacity:.42}.chips small{font:8px var(--font-press),monospace}.assembled{border:3px solid var(--line);background:#141225;color:#fff;padding:13px;min-height:50px;margin:12px 0;font-family:ui-monospace,monospace}.feedbackPanel{text-align:center}.feedbackPanel.ok{background:#d9f7e8}.feedbackPanel.bad{background:#ffe0dd}.runRobot{font-size:58px;display:flex;justify-content:center;align-items:center;gap:20px}.runRobot i{font-style:normal;font-size:30px}.missing{display:flex;gap:8px;justify-content:center;flex-wrap:wrap}.missing b{background:#fff;border:2px solid var(--line);padding:7px}.lesson{margin:18px 0;text-align:left}.lesson span,.lesson strong{display:block}.lesson span{font-size:9px;margin-bottom:6px}.promptReport .mastery{background:var(--blue)}.remixCard{display:grid;grid-template-columns:auto 1fr auto;gap:14px;align-items:center;margin:16px 0;background:var(--yellow)}.remixCard>div:first-child{font-size:44px}.remixCard h3{font-size:12px;margin:0 0 7px}.remixCard p{margin:0}.remixCard a{text-decoration:none;text-align:center}@media(max-width:640px){.pcHero{grid-template-columns:1fr 90px}.robot{width:82px;height:82px;font-size:42px}.robot i{font-size:16px}.chips{grid-template-columns:1fr}.scene span{font-size:24px}.remixCard{grid-template-columns:auto 1fr}.remixCard a{grid-column:1/-1}.title{font-size:clamp(25px,9vw,42px)}}`;

