"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { toPng } from "html-to-image";
import QRCode from "qrcode";
import { AiQuestFooter, getAiGameStats, getAiProfile, type AiGameStats } from "./dx3xb-ai";
import { evaluate, mastery, missionForSeed, resultKey, type Monster, type Species, type TrainingLabel } from "./game";

type Lang = "zh" | "en";
type Phase = "intro" | "label" | "trained" | "result";
const COPY = {
  zh: {
    kicker:"AI 探险 · 任务 02", title:"数据怪兽训练营", sub:"给怪兽贴标签，再看你训练出的分类器会不会翻车。", intro:"机器不会凭空认识怪兽。它从你给的样本和标签里找规律——标签错了、样本偏了，模型也会跟着学歪。", rule1:"标注 8 只训练怪兽", rule2:"用 6 只未见样本测试", rule3:"结果是真实计算，不是随机段位", start:"开始标注 →", daily:"今日任务", classLabel:"班级挑战", labelling:(n:number)=>`训练样本 ${n}/8`, ask:"它属于哪一族？", momo:"糯糯族", spike:"尖尖族", momoHint:"圆滚、斑点多", spikeHint:"角多、轮廓硬", train:"启动分类器 →", ready:"8 份标签已装进训练箱", readyDesc:"现在模型会计算两族样本的特征中心，再判断新怪兽离哪一族更近。", testTitle:"未见样本测试", resultKicker:"TRAINING REPORT", tested:(n:number)=>`正确识别 ${n}/6`, labels:(n:number)=>`标签判断 ${n}/8`, accuracy:"测试准确率", mastery:"数据训练掌握度", learning:"你刚刚做了什么", learningText:"你亲手提供标签，用训练集建立分类器，再用模型没见过的测试集验证。测试集不能拿去偷偷训练。", realStats:"真实关卡统计", real:(s:AiGameStats)=>`已有 ${s.plays} 次训练 · 平均掌握度 ${s.averageMastery}% · 今日完成 ${s.dailyCompletions} 次`, noStats:"你是首批训练员，统计会在战报保存后更新。", replay:"再训一次", newSet:"换一批怪兽", share:"分享挑战", copy:"复制链接", copied:"已复制", download:"保存战报", passport:"继续 AI 探险", titles:{scientist:["数据科学家","样本、标签、测试集，你都安排得明明白白。"],trainer:["怪兽训练师","模型已经能干活，再检查几枚标签会更稳。"],collector:["样本收藏家","先让两族样本都够多、标签更准确，再训练一次。"]} as Record<string,[string,string]>, anon:"匿名训练员", lang:"EN"
  },
  en: {
    kicker:"AI ADVENTURE · MISSION 02", title:"Data Monster Camp", sub:"Label monsters, then see whether your classifier learned the right pattern.", intro:"A machine does not magically know monsters. It learns patterns from the samples and labels you provide—bad labels or lopsided data create bad behavior.", rule1:"Label 8 training monsters", rule2:"Test on 6 unseen samples", rule3:"Every metric is computed from your model", start:"START LABELING →", daily:"DAILY MISSION", classLabel:"CLASS CHALLENGE", labelling:(n:number)=>`TRAINING SAMPLE ${n}/8`, ask:"Which species is it?", momo:"MOMO", spike:"SPIKE", momoHint:"rounder, more spots", spikeHint:"more horns, sharper shape", train:"RUN CLASSIFIER →", ready:"8 LABELS LOADED", readyDesc:"The model calculates a feature center for each species, then assigns new monsters to the nearest one.", testTitle:"UNSEEN TEST SET", resultKicker:"TRAINING REPORT", tested:(n:number)=>`${n}/6 correctly classified`, labels:(n:number)=>`${n}/8 labels correct`, accuracy:"test accuracy", mastery:"data mastery", learning:"WHAT YOU JUST DID", learningText:"You supplied labels, trained a classifier, then checked it on data the model had never seen. A test set must stay separate from training.", realStats:"REAL MISSION STATS", real:(s:AiGameStats)=>`${s.plays} training runs · ${s.averageMastery}% average mastery · ${s.dailyCompletions} today`, noStats:"You are among the first trainers. Stats update after this report saves.", replay:"TRAIN AGAIN", newSet:"NEW MONSTERS", share:"SHARE CHALLENGE", copy:"COPY LINK", copied:"COPIED", download:"SAVE REPORT", passport:"CONTINUE ADVENTURE", titles:{scientist:["DATA SCIENTIST","Samples, labels and test data—all under control."],trainer:["MONSTER TRAINER","The model works. A few cleaner labels will make it stronger."],collector:["SAMPLE COLLECTOR","Balance both species and clean up labels, then train again."]} as Record<string,[string,string]>, anon:"ANONYMOUS TRAINER", lang:"中"
  }
} as const;

function safeSeed(value:string|null){return (value||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,48)}
function makeSeed(){return Math.random().toString(36).slice(2,10)}
function initialLang():Lang{const p=new URLSearchParams(location.search).get("lang");const s=localStorage.getItem("dx3xb_lang");return p==="en"||(!p&&s==="en")?"en":"zh"}
function MonsterCard({monster,label}:{monster:Monster;label?:string}){
  const color=`hsl(${Math.round(monster.hue*250+20)} 72% 64%)`;
  return <div className="monster" style={{"--monster":color,"--round":`${8+monster.round*42}%`} as React.CSSProperties} aria-label={label}>
    <i className="horns" aria-hidden="true">{"▲".repeat(monster.horns)}</i><span className="face" aria-hidden="true"><b>•‿•</b>{Array.from({length:monster.spots},(_,i)=><em key={i}>◆</em>)}</span>
  </div>
}

export default function DataMonsterPage(){
  const [hydrated,setHydrated]=useState(false),[lang,setLang]=useState<Lang>("zh"),[seed,setSeed]=useState("data-monster"),[phase,setPhase]=useState<Phase>("intro"),[idx,setIdx]=useState(0),[labels,setLabels]=useState<TrainingLabel[]>([]),[labelCorrect,setLabelCorrect]=useState(0),[profile,setProfile]=useState(""),[dailyDate,setDailyDate]=useState(""),[classCode,setClassCode]=useState(""),[stats,setStats]=useState<AiGameStats|null>(null),[qr,setQr]=useState(""),[copied,setCopied]=useState(false),[saving,setSaving]=useState(false);
  const started=useRef(Date.now()),reportRef=useRef<HTMLDivElement>(null);
  const mission=useMemo(()=>missionForSeed(seed),[seed]);
  const outcome=useMemo(()=>evaluate(labels,mission.test),[labels,mission.test]);
  const masteryValue=mastery(labelCorrect,mission.training.length,outcome.accuracy);
  const score=masteryValue*10+Math.max(0,120-Math.round((Date.now()-started.current)/1000));
  const t=COPY[lang],title=t.titles[resultKey(masteryValue)],name=profile||t.anon;
  useEffect(()=>{const p=new URLSearchParams(location.search);setLang(initialLang());setSeed(safeSeed(p.get("seed"))||makeSeed());setDailyDate(/^\d{4}-\d{2}-\d{2}$/.test(p.get("daily")||"")?p.get("daily")||"":"");setClassCode(/^[A-Z2-9]{6}$/.test((p.get("class")||"").toUpperCase())?(p.get("class")||"").toUpperCase():"");getAiProfile().then(x=>setProfile((x.handle||"").slice(0,24))).catch(()=>{});setHydrated(true)},[]);
  const challengeUrl=useMemo(()=>{const u=new URL(typeof location==="undefined"?"https://data-monster.dx3xb.com":location.origin);u.searchParams.set("seed",seed);u.searchParams.set("lang",lang);if(classCode)u.searchParams.set("class",classCode);return u.toString()},[classCode,lang,seed]);
  useEffect(()=>{if(phase!=="result")return;QRCode.toDataURL(challengeUrl,{margin:1,width:220,color:{dark:"#221a2b",light:"#fffdf8"}}).then(setQr).catch(()=>setQr(""));getAiGameStats().then(setStats).catch(()=>{})},[challengeUrl,phase]);
  function start(next=seed){setSeed(next);setPhase("label");setIdx(0);setLabels([]);setLabelCorrect(0);setStats(null);started.current=Date.now()}
  function label(species:Species){const monster=mission.training[idx];setLabels(x=>[...x,{monster,label:species}]);if(species===monster.truth)setLabelCorrect(x=>x+1);if(idx===mission.training.length-1)setPhase("trained");else setIdx(x=>x+1)}
  function finish(){setPhase("result")}
  function fresh(){const s=makeSeed();const u=new URL(location.href);u.searchParams.set("seed",s);u.searchParams.delete("daily");history.replaceState(null,"",u);setDailyDate("");start(s)}
  function switchLang(){const n=lang==="zh"?"en":"zh";setLang(n);localStorage.setItem("dx3xb_lang",n);const u=new URL(location.href);u.searchParams.set("lang",n);history.replaceState(null,"",u)}
  async function copy(){await navigator.clipboard.writeText(challengeUrl);setCopied(true);setTimeout(()=>setCopied(false),1500)}
  async function share(){if(navigator.share)await navigator.share({title:t.title,text:title[0],url:challengeUrl}).catch(()=>{});else await copy()}
  async function download(){if(!reportRef.current)return;setSaving(true);try{const url=await toPng(reportRef.current,{pixelRatio:2,backgroundColor:"#fff7e7"});const a=document.createElement("a");a.download=`dx3xb-data-monster-${seed}.png`;a.href=url;a.click()}finally{setSaving(false)}}
  const run=useMemo(()=>({score,pct:masteryValue,title:title[0],lang,handle:name,stats:{seed,labels:mission.training.length,labelCorrect,testSize:mission.test.length,testCorrect:outcome.correct,accuracy:outcome.accuracy,...(dailyDate?{dailyDate}:{}),...(classCode?{classCode}:{})}}),[classCode,dailyDate,labelCorrect,lang,masteryValue,mission.test.length,mission.training.length,name,outcome.accuracy,outcome.correct,score,seed,title]);
  return <main className="wrap gameWrap" data-testid="game-root" data-hydrated={hydrated?"true":"false"}><style dangerouslySetInnerHTML={{__html:STYLE}}/>
    <div className="backbar"><a className="backbtn" href="https://dx3xb.com">← dx3xb</a><button className="langbtn" onClick={switchLang}>{t.lang}</button></div>
    <header className="questHero"><div><p className="labKicker">{t.kicker}</p><h1 className="pixel title">{t.title}</h1><p className="subtitle pixel">{t.sub}</p></div><div className="heroMonster"><MonsterCard monster={{id:"hero",round:.9,horns:1,spots:3,hue:.4,truth:"momo"}}/></div></header>
    {(dailyDate||classCode)&&<div className="missionStrip">{dailyDate&&<b>☀ {t.daily} · {dailyDate}</b>}{classCode&&<b>🏫 {t.classLabel} · {classCode}</b>}</div>}
    {phase==="intro"&&<section className="panel introPanel"><p className="introText">{t.intro}</p><div className="rules"><span>1</span><p>{t.rule1}</p><span>2</span><p>{t.rule2}</p><span>3</span><p>{t.rule3}</p></div><button className="btn coral" onClick={()=>start()}>{t.start}</button></section>}
    {phase==="label"&&<section className="panel labPanel"><div className="progressLine"><b className="pixel">{t.labelling(idx+1)}</b><i><span style={{width:`${((idx+1)/8)*100}%`}}/></i></div><MonsterCard monster={mission.training[idx]} label={t.ask}/><h2>{t.ask}</h2><div className="labelButtons"><button className="btn teal" onClick={()=>label("momo")}><b>{t.momo}</b><small>{t.momoHint}</small></button><button className="btn coral" onClick={()=>label("spike")}><b>{t.spike}</b><small>{t.spikeHint}</small></button></div></section>}
    {phase==="trained"&&<section className="panel trainedPanel"><div className="crate" aria-hidden="true">🗃️<b>8</b></div><h2 className="pixel">{t.ready}</h2><p>{t.readyDesc}</p><div className="dataset">{mission.training.map((m,i)=><span key={m.id} className={labels[i]?.label===m.truth?"ok":"bad"}>{labels[i]?.label==="momo"?"●":"▲"}</span>)}</div><button className="btn coral" onClick={finish}>{t.train}</button></section>}
    {phase==="result"&&<><section className="resultShell"><div className="reportCard monsterReport" ref={reportRef}><div className="reportTop"><p className="labKicker">{t.resultKicker}</p><span>MODEL v1.0</span></div><p className="issued">{name}</p><h2 className="pixel resultName">{title[0]}</h2><p className="resultDesc">{title[1]}</p><div className="mastery"><b>{masteryValue}<span>%</span></b><p>{t.mastery}</p></div><div className="reportGrid"><div><b>{labelCorrect}/8</b><span>{t.labels(labelCorrect)}</span></div><div><b>{outcome.accuracy}%</b><span>{t.accuracy}</span></div><div><b>{outcome.correct}/6</b><span>{t.tested(outcome.correct)}</span></div></div><div className="predictionGrid">{outcome.predictions.map(row=><span key={row.monster.id} className={row.correct?"ok":"bad"}>{row.predicted==="momo"?"●":"▲"}<small>{row.correct?"✓":"×"}</small></span>)}</div><div className="learningCard"><span className="pixel">{t.learning}</span><strong>{t.learningText}</strong></div><div className="reportShare">{qr&&<img src={qr} alt="challenge QR"/>}<div><p className="pixel">DATA MONSTER</p><small>data-monster.dx3xb.com</small></div></div></div>
    <div className="panel realStats"><h3 className="pixel">{t.realStats}</h3><p>{stats&&stats.plays>0?t.real(stats):t.noStats}</p></div><div className="actions resultActions"><button className="btn coral" onClick={download} disabled={saving}>{saving?"…":t.download}</button><button className="btn teal" onClick={share}>{t.share}</button><button className="btn ghost" onClick={copy}>{copied?t.copied:t.copy}</button><button className="btn ghost" onClick={()=>start()}>{t.replay}</button><button className="btn ghost" onClick={fresh}>{t.newSet}</button></div><AiQuestFooter lang={lang} run={run}/></section></>}
  </main>
}

const STYLE=`
.gameWrap{max-width:860px}.questHero{display:grid;grid-template-columns:1fr 180px;align-items:center;gap:20px;margin-bottom:20px}.heroMonster{transform:rotate(4deg)}.missionStrip{display:flex;gap:10px;flex-wrap:wrap;margin:-4px 0 16px}.missionStrip b{background:var(--yellow);border:3px solid var(--line);padding:7px 10px;font:11px var(--font-press),monospace}.labPanel,.trainedPanel{text-align:center}.progressLine{display:flex;align-items:center;gap:14px;text-align:left}.progressLine b{font-size:10px}.progressLine i{height:14px;border:3px solid var(--line);flex:1;background:#fff}.progressLine i span{display:block;height:100%;background:var(--teal)}.monster{width:min(240px,70vw);aspect-ratio:1;margin:20px auto;position:relative;display:grid;place-items:center}.face{width:76%;height:72%;border:5px solid var(--line);border-radius:var(--round);background:var(--monster);box-shadow:7px 7px 0 var(--ink);display:grid;place-items:center;position:relative;font-size:30px}.face em{position:absolute;font-style:normal;font-size:12px;color:#fff}.face em:nth-of-type(1){left:17%;top:22%}.face em:nth-of-type(2){right:16%;top:28%}.face em:nth-of-type(3){left:28%;bottom:17%}.face em:nth-of-type(4){right:25%;bottom:14%}.horns{position:absolute;z-index:2;top:0;letter-spacing:10px;font-size:28px;color:var(--coral);font-style:normal}.labelButtons{display:grid;grid-template-columns:1fr 1fr;gap:14px}.labelButtons button{display:grid;gap:4px}.labelButtons small{font:14px var(--font-body),sans-serif}.crate{font-size:86px;position:relative}.crate b{position:absolute;left:50%;top:48%;transform:translate(-50%,-50%);font:16px var(--font-press),monospace}.dataset,.predictionGrid{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin:18px 0}.dataset span,.predictionGrid span{width:42px;height:42px;display:grid;place-items:center;border:3px solid var(--line);background:#fff;font-weight:bold}.dataset .ok,.predictionGrid .ok{background:#bff3d8}.dataset .bad,.predictionGrid .bad{background:#ffc7c3}.predictionGrid small{font-size:12px}.realStats{margin:16px 0;background:var(--yellow)}.realStats h3{font-size:11px;margin:0 0 8px}.realStats p{margin:0}.monsterReport{background:#fff7e7}.monsterReport .mastery{background:var(--teal)}
@media(max-width:640px){.questHero{grid-template-columns:1fr 100px}.heroMonster .monster{width:100px}.heroMonster .face{font-size:18px}.labelButtons{grid-template-columns:1fr}.reportGrid{grid-template-columns:1fr}.monster{margin:12px auto}.title{font-size:clamp(25px,9vw,42px)}}
`;

